'use client';
import {type CSSProperties} from 'react';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {FAQSection} from '@/components/FAQSection';
import {brands,cities} from './family-content';
import {ApprovedEstimate} from './ApprovedEstimate';
const Arrow=()=> <ArrowUpRight size={18} aria-hidden="true"/>;
function Title({lines}:{lines:string[]}){return <>{lines[0]}<br/><em>{lines[1]}</em></>}
function Rows({items,numbered=false}:{items:[string,string][];numbered?:boolean}){return <Accordion type="single" collapsible defaultValue="0" className="f-accordion">{items.map(([title,copy],i)=><AccordionItem value={String(i)} key={title}><AccordionTrigger>{numbered&&<span className="f-number">0{i+1}</span>}<span>{title}</span></AccordionTrigger><AccordionContent>{copy}</AccordionContent></AccordionItem>)}</Accordion>}

export function ApprovedHome(){const b=brands['remodeling'];const home='';const primary='/estimate';const contact='/contact';
 const contactBlock=<section className="f-contact" id="contact"><div className="f-container f-two"><div><p className="f-eyebrow">LET'S TALK ABOUT YOUR HOME</p><h2><Title lines={b.contactTitle}/></h2><p>{b.contactText}</p><a className="f-button" href={primary}>{b.action}<Arrow/></a><a className="estimate-secondary" href={contact}>{b.id==='adu'?'Prefer to talk about your property?':'Prefer a conversation? Contact our team'}<Arrow/></a></div><div className="f-contact-details"><p className="f-eyebrow">A USEFUL STARTING POINT</p><h3>{b.id==='handyman'?'Your tasks, photos, and priorities.':b.id==='adu'?'Your property, ideas, and questions.':'Your ideas, priorities, and questions.'}</h3><p>{b.id==='handyman'?'Share the full list and any timing needs so we can plan the scope and materials.':b.id==='adu'?'An address, a few photos, and your intended use help start the feasibility conversation.':'There is no need to have every selection made. Start with what you know, and we will work through the rest together.'}</p><a href="tel:+12084771169">(208) 477-1169 <Arrow/></a><a href="sms:+12084771169">Send a text <Arrow/></a><span>Meridian, Idaho · Treasure Valley</span></div></div></section>;
 const processBlock=<section className="f-section f-container f-two" id="how-we-build"><div className="f-sticky"><p className="f-eyebrow">KNOW WHAT HAPPENS NEXT</p><h2>A clear plan.<br/><em>At every step.</em></h2><p>Good work starts with a shared understanding of the scope, the decisions, and the next step.</p></div><Rows items={b.process} numbered/></section>;
 const approachBlock=<section className="f-section f-container f-two" id="why-choose-us"><div className="f-sticky"><p className="f-eyebrow">THE WAY WE WORK</p><h2>Good work.<br/><em>A better experience.</em></h2><p>{b.id==='handyman'?'Small jobs deserve a clear quote, a dependable visit, and a tidy finish.':'Clear expectations, thoughtful decisions, and someone accountable for the work. That is the P5 standard.'}</p></div><Rows items={b.approach}/></section>;

return <div className={`family-site family-${b.id}`} style={{'--f-accent':b.accent} as CSSProperties}>
 <section className="f-hero"><img src={b.hero} alt={b.id==='construction'?'White home with a welcoming covered porch':b.id==='remodeling'?'Open kitchen and living space with warm wood and stone':b.id==='handyman'?'Careful adjustment of an interior door hinge':'Compact detached dwelling with cedar accents and a covered entrance'} fetchPriority="high" width="1600" height="1000"/><div className="f-hero-shade"/><div className="f-hero-copy"><p className="f-eyebrow">{b.kicker}</p><h1><Title lines={b.title}/></h1><p>{b.intro}</p><div className="f-actions"><a className="f-button" href={primary}>{b.action}<Arrow/></a><a className="f-link" href="#services">{b.secondary}<ArrowRight size={18}/></a></div><span className="estimator-promise">Describe your project. Get a preliminary estimate online.</span></div></section>
 <div className="f-proof">{b.proof.map((p,i)=><div key={p}><span>0{i+1}</span><p>{p}</p></div>)}</div>
 <section className="f-section f-container" id="services"><div className="f-section-top"><div><p className="f-eyebrow">FIND YOUR STARTING POINT</p><h2><Title lines={b.serviceTitle}/></h2></div><p>{b.serviceIntro}</p></div><Tabs defaultValue={b.services[0].slug} className="f-explorer"><TabsList className="f-tabs">{b.services.slice(0,3).map(s=><TabsTrigger value={s.slug} key={s.slug}>{s.name}</TabsTrigger>)}</TabsList>{b.services.slice(0,3).map((s,i)=><TabsContent key={s.slug} value={s.slug}><div className="f-scene"><a className="f-scene-image" href={s.live || `/services/${s.slug}`} aria-label={`Explore ${s.name.toLowerCase()}`}><img src={s.image} alt={s.name} loading="lazy" width="1000" height="750"/></a><div className="f-scene-copy"><p className="f-eyebrow">0{i+1} / {b.name.replace('Boise ','')}</p><h3>{s.name}</h3><p>{s.summary}</p><ul>{s.includes.slice(0,2).map(t=><li key={t}>{t}</li>)}</ul><a className="f-link" href={s.live || `/services/${s.slug}`}>Explore this service <Arrow/></a></div></div></TabsContent>)}</Tabs><a className="f-link f-browse-all" href={`${home}/services`}>View all services <Arrow/></a></section>
 <ApprovedEstimate/>


 <section className="f-value"><img src={b.valueImage} alt={b.id==='handyman'?'Finish carpentry and trim work':b.id==='construction'?'Coordinated framing and mechanical rough-in':b.id==='adu'?'A home and its surrounding property':'Materials and careful preparation for remodeling'} loading="lazy" width="1200" height="900"/><div><p className="f-eyebrow">{b.id==='adu'?'A SOUND STARTING POINT':'WHERE YOUR MONEY GOES'}</p><h2><Title lines={b.valueTitle}/></h2><p>{b.value}</p><a className="f-link" href={primary}>{b.action}<Arrow/></a></div></section>
 {approachBlock}{processBlock}
 <section className="f-image-pair f-container"><img src={b.services[1].image} alt={b.services[1].name} loading="lazy" width="1000" height="800"/><div><img src={b.services[2].image} alt={b.services[2].name} loading="lazy" width="900" height="675"/><p className="f-eyebrow">{b.id==='handyman'?'CARE IN THE SMALL DETAILS.':'A HOME THAT WORKS FOR YOU.'}</p><h3>{b.id==='handyman'?'You notice the difference. Every day.':'Thoughtful spaces. Everyday living.'}</h3></div></section>
 <section className="f-area f-section f-container"><p className="f-eyebrow">AT HOME IN IDAHO</p><h2>Local people.<br/><em>Valley-wide reach.</em></h2><p>Serving homeowners throughout the Treasure Valley.</p><div>{cities.map(city=><a key={city} href={b.id==='adu'?`${home}/contact`:`/areas/${city.toLowerCase().replaceAll(" ","-")}`}>{city}<Arrow/></a>)}</div></section>
 <FAQSection/>{contactBlock}
 </div>;}
