/**
 * Per-slug blog and guide imagery - single source of truth.
 * Generated by scripts/generate-blog-image-registry.mjs - do not hand-edit entries.
 * Re-run the generator after changing slug mappings, then npm run images:blog.
 */

export type BlogImageSource = 'blog' | 'gallery' | 'city-service' | 'areas' | 'services';

export interface BlogImageEntry {
  hero: string;
  thumbnail?: string;
  alt: string;
  topicTags: string[];
  source: BlogImageSource;
}

export const BLOG_IMAGE_REGISTRY: Record<string, BlogImageEntry> = {
  'kitchen-remodel-cost-boise': {
    hero: '/images/blog/kitchen-remodel-cost-boise.webp',
    alt: 'Remodeled Boise kitchen with warm walnut cabinetry, a quartz island, and Boise foothills views',
    topicTags: ["kitchen","cost","boise"],
    source: 'blog',
  },
  'bathroom-remodel-cost-boise': {
    hero: '/images/blog/bathroom-remodel-cost-boise.webp',
    alt: 'Remodeled Boise primary bathroom with a walk-in glass shower, freestanding tub, and warm wood vanity',
    topicTags: ["bathroom","cost","boise"],
    source: 'blog',
  },
  'whole-home-remodel-cost-boise': {
    hero: '/images/blog/whole-home-remodel-cost-boise.webp',
    alt: 'Whole-home remodel great room in a Boise house with a vaulted beamed ceiling and stone fireplace',
    topicTags: ["whole-home","cost","boise"],
    source: 'blog',
  },
  'home-addition-cost-boise': {
    hero: '/images/blog/home-addition-cost-boise.webp',
    alt: 'Modern home addition on a Boise house glowing at dusk with foothills behind',
    topicTags: ["addition","cost","boise"],
    source: 'blog',
  },
  'luxury-remodel-cost-boise': {
    hero: '/images/blog/luxury-remodel-cost-boise.webp',
    alt: 'Luxury remodeled kitchen in an Eagle foothills home with a waterfall stone island and custom walnut cabinetry',
    topicTags: ["luxury","cost","eagle"],
    source: 'blog',
  },
  'remodel-cost-per-square-foot-boise': {
    hero: '/images/blog/remodel-cost-per-square-foot-boise.webp',
    alt: 'Bright open-concept living and dining space in a remodeled Boise home with light oak floors',
    topicTags: ["cost","whole-home","boise"],
    source: 'blog',
  },
  'what-impacts-remodeling-costs-boise': {
    hero: '/images/blog/what-impacts-remodeling-costs-boise.webp',
    alt: 'Refined Boise home den with floor-to-ceiling custom built-in shelving and a fireplace',
    topicTags: ["cost","planning","process"],
    source: 'blog',
  },
  'how-to-budget-remodel-boise': {
    hero: '/images/blog/how-to-budget-remodel-boise.webp',
    alt: 'Warm home office nook in a remodeled Boise home with a wood desk and built-in shelving',
    topicTags: ["cost","budget","planning"],
    source: 'blog',
  },
  'kitchen-remodel-timeline-boise': {
    hero: '/images/blog/kitchen-remodel-timeline-boise.webp',
    alt: 'Bright modern farmhouse kitchen in a remodeled Boise home with white cabinetry and a sage-green island',
    topicTags: ["kitchen","timeline","boise"],
    source: 'blog',
  },
  'kitchen-layout-ideas-boise-homes': {
    hero: '/images/blog/kitchen-layout-ideas-boise-homes.webp',
    alt: 'Large open-concept kitchen with a central island and walk-in pantry in a remodeled Boise home',
    topicTags: ["kitchen","layout","boise"],
    source: 'blog',
  },
  'kitchen-cabinet-trends': {
    hero: '/images/city-service/kitchen-remodel__kuna.webp',
    alt: 'Modern kitchen cabinetry with warm wood tones in a Kuna home',
    topicTags: ["kitchen","cabinets","kuna"],
    source: 'city-service',
  },
  'quartz-vs-quartzite-kitchen': {
    hero: '/images/city-service/kitchen-remodel__star.webp',
    alt: 'Kitchen countertop detail showing quartz surfaces in a Star-area home',
    topicTags: ["kitchen","countertops","star"],
    source: 'city-service',
  },
  'kitchen-remodel-roi': {
    hero: '/images/blog/kitchen-remodel-roi.webp',
    alt: "Updated transitional kitchen with an island and quality finishes illustrating strong remodel return on investment in a Boise home",
    topicTags: ["kitchen","roi","boise"],
    source: 'blog',
  },
  'open-concept-kitchen-remodeling': {
    hero: '/images/blog/open-concept-kitchen-remodeling.webp',
    alt: 'Open-concept kitchen with a large central island flowing into the living area after wall removal in an upscale Boise home',
    topicTags: ["kitchen","open-concept","boise"],
    source: 'blog',
  },
  'kitchen-island-design-guide': {
    hero: '/images/blog/kitchen-island-design-guide.webp',
    alt: 'Large kitchen island with counter seating, pendant lights, and a waterfall quartz edge in a remodeled Boise home',
    topicTags: ["kitchen","island","boise"],
    source: 'blog',
  },
  'kitchen-cabinet-trends-boise': {
    hero: '/images/blog/kitchen-cabinet-trends-boise.webp',
    alt: 'Two-tone kitchen with sage-green lower cabinets, white uppers, and warm wood open shelving in a Boise remodel',
    topicTags: ["kitchen","cabinets","boise"],
    source: 'blog',
  },
  'quartz-vs-quartzite-countertops': {
    hero: '/images/blog/quartz-vs-quartzite-countertops.webp',
    alt: 'Kitchen with a dramatic natural quartzite island and countertops with bold veining in a Boise home',
    topicTags: ["kitchen","countertops","boise"],
    source: 'blog',
  },
  'small-kitchen-remodel-ideas-boise': {
    hero: '/images/blog/small-kitchen-remodel-ideas-boise.webp',
    alt: 'Compact remodeled galley kitchen with white cabinets and open shelving in a modest older Boise bungalow',
    topicTags: ["kitchen","small","boise"],
    source: 'blog',
  },
  'walk-in-pantry-design-guide': {
    hero: '/images/city-service/kitchen-remodel__caldwell.webp',
    alt: 'Walk-in pantry with custom shelving in a Caldwell kitchen remodel',
    topicTags: ["kitchen","pantry","caldwell"],
    source: 'city-service',
  },
  'walk-in-shower-guide': {
    hero: '/images/blog/walk-in-shower-guide.webp',
    alt: 'Large walk-in shower with a frameless glass enclosure, floor-to-ceiling tile, and a built-in niche and bench in a remodeled Boise bathroom',
    topicTags: ["bathroom","shower","boise"],
    source: 'blog',
  },
  'curbless-shower-guide': {
    hero: '/images/blog/curbless-shower-guide.webp',
    alt: 'Curbless zero-threshold walk-in shower with a flush tile floor and linear drain in an accessible Boise bathroom',
    topicTags: ["bathroom","shower","accessibility","boise"],
    source: 'blog',
  },
  'luxury-bathroom-features': {
    hero: '/images/blog/luxury-bathroom-features.webp',
    alt: 'Luxury primary bathroom with a freestanding soaking tub, frameless glass shower, double vanity, and marble-look tile in an upscale Eagle-area home',
    topicTags: ["bathroom","luxury","boise"],
    source: 'blog',
  },
  'how-long-does-a-bathroom-remodel-take': {
    hero: '/images/blog/how-long-does-a-bathroom-remodel-take.webp',
    alt: 'Freshly completed mid-range bathroom remodel with a navy vanity, white quartz top, and tiled shower-tub in a Boise home',
    topicTags: ["bathroom","timeline","boise"],
    source: 'blog',
  },
  'small-bathroom-remodel-ideas': {
    hero: '/images/blog/small-bathroom-remodel-ideas.webp',
    alt: 'Compact remodeled bathroom with a shower-tub combo, single vanity, and light finishes in a modest older Boise home',
    topicTags: ["bathroom","small","boise"],
    source: 'blog',
  },
  'aging-in-place-bathroom-design': {
    hero: '/images/blog/aging-in-place-bathroom-design.webp',
    alt: 'Accessible aging-in-place bathroom with a curbless walk-in shower, bench, integrated grab bars, and comfort-height vanity in a Boise home',
    topicTags: ["bathroom","aging-in-place","boise"],
    source: 'blog',
  },
  'bathroom-remodel-roi': {
    hero: '/images/blog/bathroom-remodel-roi.webp',
    alt: "Updated bathroom with a walk-in shower and quality vanity illustrating strong remodel return on investment in a Boise home",
    topicTags: ["bathroom","roi","boise"],
    source: 'blog',
  },
  'bathroom-layout-planning-guide': {
    hero: '/images/blog/bathroom-layout-planning-guide.webp',
    alt: 'Well-planned classic full bathroom with a white vanity, separate tub and glass shower, subway tile, and hex-tile floor in a Boise home',
    topicTags: ["bathroom","layout","boise"],
    source: 'blog',
  },
  'primary-suite-additions': {
    hero: '/images/blog/primary-suite-additions.webp',
    alt: 'Spacious primary suite addition with a vaulted ceiling, sitting area, and ensuite glimpse in an upscale Boise home',
    topicTags: ["addition","primary-suite","boise"],
    source: 'blog',
  },
  'adu-cost-boise': {
    hero: '/images/blog/adu-cost-boise.webp',
    alt: 'Detached accessory dwelling unit backyard cottage with lap siding and a covered porch in a Boise backyard',
    topicTags: ["adu","addition","boise"],
    source: 'blog',
  },
  'basement-finishing-boise': {
    hero: '/images/blog/basement-finishing-boise.webp',
    alt: 'Finished basement family room with a sectional, media area, egress window, and warm neutral finishes in a Boise home',
    topicTags: ["addition","basement","boise"],
    source: 'blog',
  },
  'bedroom-additions': {
    hero: '/images/blog/bedroom-additions.webp',
    alt: 'Bright new bedroom addition with large windows, neutral walls, and a wood floor in a Boise home',
    topicTags: ["addition","bedroom","boise"],
    source: 'blog',
  },
  'second-story-additions': {
    hero: '/images/blog/second-story-additions.webp',
    alt: 'Completed second-story addition on a former single-story Boise ranch with matching siding and roofline',
    topicTags: ["addition","second-story","boise"],
    source: 'blog',
  },
  'garage-conversions': {
    hero: '/images/blog/garage-conversions.webp',
    alt: 'Converted garage finished as a bright bonus room and home office with new windows and luxury vinyl plank flooring in a Boise home',
    topicTags: ["addition","garage-conversion","boise"],
    source: 'blog',
  },
  'adu-guide-boise': {
    hero: '/images/city-service/adu__boise.webp',
    alt: 'Accessory dwelling unit completed in a Boise backyard with separate entry',
    topicTags: ["adu","addition","boise"],
    source: 'city-service',
  },
  'multigenerational-living-remodels': {
    hero: '/images/blog/multigenerational-living-remodels.webp',
    alt: 'In-law suite for multigenerational living with a compact kitchenette and sitting area in a Boise home',
    topicTags: ["adu","addition","multigenerational","boise"],
    source: 'blog',
  },
  'home-addition-timeline-guide': {
    hero: '/images/blog/home-addition-timeline-guide.webp',
    alt: 'Home addition under construction with new framing, roof trusses, and foundation tied into an existing Boise house',
    topicTags: ["addition","timeline","boise"],
    source: 'blog',
  },
  'room-addition-guide-treasure-valley': {
    hero: '/images/gallery/gallery-addition-after.webp',
    alt: 'Completed room addition blending with original Treasure Valley home architecture',
    topicTags: ["addition","treasure-valley"],
    source: 'gallery',
  },
  'remodeling-vs-moving': {
    hero: '/images/blog/remodeling-vs-moving.webp',
    alt: 'Beautifully renovated single-family home exterior with fresh siding, updated windows, and a covered porch in a Boise neighborhood',
    topicTags: ["whole-home","planning","boise"],
    source: 'blog',
  },
  'whole-home-remodel-timeline': {
    hero: '/images/blog/whole-home-remodel-timeline.webp',
    alt: 'Whole-home renovation in progress, an interior stripped to the studs with new wiring and floor protection in a Boise house',
    topicTags: ["whole-home","timeline","boise"],
    source: 'blog',
  },
  'living-through-a-remodel': {
    hero: '/images/blog/living-through-a-remodel.webp',
    alt: 'Home lived in during renovation with a plastic dust barrier separating the construction zone from a living area with covered furniture',
    topicTags: ["whole-home","living-in-place","boise"],
    source: 'blog',
  },
  'remodel-planning-guide': {
    hero: '/images/city-service/whole-home-remodel__middleton.webp',
    alt: 'Remodel planning session in a Middleton home with design selections underway',
    topicTags: ["whole-home","planning","middleton"],
    source: 'city-service',
  },
  'remodeling-mistakes-to-avoid': {
    hero: '/images/blog/remodeling-mistakes-to-avoid.webp',
    alt: 'Completed whole-home remodel with a cohesive open-concept living and dining area and quality transitional finishes in a Boise home',
    topicTags: ["whole-home","planning","boise"],
    source: 'blog',
  },
  'design-build-process-guide': {
    hero: '/images/blog/design-build-process-guide.webp',
    alt: 'Completed whole-home remodel showcasing cohesive design-build results',
    topicTags: ["whole-home","design-build"],
    source: 'blog',
  },
  'whole-home-remodel-planning-checklist': {
    hero: '/images/blog/whole-home-remodel-planning-checklist.webp',
    alt: "Remodel planning table with printed floor plans, a tape measure, a notebook, and material samples for a Boise whole-home remodel",
    topicTags: ["whole-home","planning","boise"],
    source: 'blog',
  },
  'questions-to-ask-remodeling-contractor': {
    hero: '/images/blog/questions-to-ask-remodeling-contractor.webp',
    alt: 'Warm entryway and mudroom in a remodeled Boise home with a custom built-in bench and lockers',
    topicTags: ["contractor","consultation"],
    source: 'blog',
  },
  'remodeling-contractor-red-flags': {
    hero: '/images/blog/remodeling-contractor-red-flags.webp',
    alt: 'Tidy, professional home renovation in progress in Boise with dust barriers and floor protection',
    topicTags: ["contractor","quality"],
    source: 'blog',
  },
  'design-build-vs-general-contractor': {
    hero: '/images/blog/design-build-vs-general-contractor.webp',
    alt: 'Bright breakfast nook with a built-in banquette in a remodeled Boise home',
    topicTags: ["contractor","design-build"],
    source: 'blog',
  },
  'fixed-price-vs-cost-plus': {
    hero: '/images/blog/fixed-price-vs-cost-plus.webp',
    alt: 'Refined butler’s pantry and home bar in a remodeled Boise home with floor-to-ceiling cabinetry',
    topicTags: ["contractor","pricing"],
    source: 'blog',
  },
  'how-to-compare-remodeling-estimates': {
    hero: '/images/blog/how-to-compare-remodeling-estimates.webp',
    alt: 'Well-organized laundry and mudroom in a remodeled Boise home with sage-green cabinetry',
    topicTags: ["contractor","estimates"],
    source: 'blog',
  },
  'why-remodeling-bids-vary': {
    hero: '/images/blog/why-remodeling-bids-vary.webp',
    alt: 'Elegant formal dining room in a remodeled Boise home with paneled walls and a statement light fixture',
    topicTags: ["contractor","pricing"],
    source: 'blog',
  },
  'what-makes-great-remodeling-contractor': {
    hero: '/images/blog/kitchen-roi-remodeling.webp',
    alt: 'Quality finished kitchen remodel showing the craftsmanship a great Treasure Valley contractor delivers',
    topicTags: ["contractor","craftsmanship"],
    source: 'blog',
  },
  'consultation-process-remodeling': {
    hero: '/images/blog/consultation-process-remodeling.webp',
    alt: "In-home remodeling design consultation on a kitchen table with printed plans, finish samples, and a laptop in a Boise home",
    topicTags: ["process","consultation","boise"],
    source: 'blog',
  },
  'how-to-choose-design-build-contractor': {
    hero: '/images/city-service/room-addition__kuna.webp',
    alt: 'Design-build remodeling team walking a room addition job site with Treasure Valley homeowners',
    topicTags: ["contractor","design-build","boise"],
    source: 'city-service',
  },
  'remodeling-timeline-guide': {
    hero: '/images/city-service/room-addition__middleton.webp',
    alt: 'Remodel project timeline phases from design through construction completion in Middleton',
    topicTags: ["process","timeline"],
    source: 'city-service',
  },
  'boise-permit-guide': {
    hero: '/images/blog/boise-permit-guide.webp',
    alt: "Architectural blueprints and construction drawings for a Boise home remodel laid out with a scale ruler and pencil",
    topicTags: ["process","permits","boise"],
    source: 'blog',
  },
  'preconstruction-guide': {
    hero: '/images/gallery/gallery-kitchen-before.webp',
    alt: 'Preconstruction planning with material samples and floor plans before demo begins',
    topicTags: ["process","preconstruction"],
    source: 'gallery',
  },
  'design-development-guide': {
    hero: '/images/gallery/gallery-bathroom-before.webp',
    alt: 'Design development selections for bathroom tile, fixtures, and finishes',
    topicTags: ["process","design"],
    source: 'gallery',
  },
  'material-selection-guide': {
    hero: '/images/blog/material-selection-guide.webp',
    alt: "Remodel material selection board with tile, quartz, wood flooring, cabinet, and hardware samples arranged for a Boise project",
    topicTags: ["process","materials","boise"],
    source: 'blog',
  },
  'construction-phase-guide': {
    hero: '/images/city-service/room-addition__caldwell.webp',
    alt: 'Active construction phase with framing and mechanical rough-in on a Caldwell room addition',
    topicTags: ["process","construction"],
    source: 'city-service',
  },
  'punch-list-guide': {
    hero: '/images/blog/punch-list-guide.webp',
    alt: 'Final walkthrough punch list review in a nearly completed remodel',
    topicTags: ["process","punch-list"],
    source: 'blog',
  },
  'warranty-guide-remodeling': {
    hero: '/images/gallery/gallery-basement-after.webp',
    alt: 'Completed basement finish detail showing warranty-worthy craftsmanship',
    topicTags: ["process","warranty"],
    source: 'gallery',
  },
  'ada-vs-canyon-county-permit-timelines': {
    hero: '/images/blog/ada-vs-canyon-county-permit-timelines.webp',
    alt: 'Treasure Valley home remodel subject to Ada or Canyon County permit review',
    topicTags: ["process","permits","ada-county","canyon-county"],
    source: 'blog',
  },
  'addition-roi-remodeling': {
    hero: '/images/city-service/room-addition__star.webp',
    alt: 'Room addition increasing livable square footage and home value in Star',
    topicTags: ["roi","addition","star"],
    source: 'city-service',
  },
  'outdoor-living-roi': {
    hero: '/images/blog/outdoor-living-roi.webp',
    alt: 'Outdoor living space with patio and landscaping boosting curb appeal',
    topicTags: ["roi","outdoor"],
    source: 'blog',
  },
  'exterior-remodeling-roi': {
    hero: '/images/blog/exterior-remodeling-roi.webp',
    alt: "Boise home exterior with fresh siding, a new entry and garage door, and tidy landscaping showing strong curb-appeal ROI",
    topicTags: ["exterior","roi","boise"],
    source: 'blog',
  },
  'energy-efficiency-roi': {
    hero: '/images/blog/energy-efficiency-roi.webp',
    alt: "Energy-efficient Boise home upgrade with insulation and efficient systems delivering lower bills and added value",
    topicTags: ["energy","roi","boise"],
    source: 'blog',
  },
  'remodeling-before-selling': {
    hero: '/images/city-service/bathroom-remodel__star.webp',
    alt: 'Updated bathroom and finishes staged before listing a Treasure Valley home for sale',
    topicTags: ["roi","selling","bathroom"],
    source: 'city-service',
  },
  'remodeling-long-term-living': {
    hero: '/images/city-service/adu__caldwell.webp',
    alt: 'ADU and whole-home updates tailored for long-term multigenerational living in Caldwell',
    topicTags: ["roi","long-term","caldwell"],
    source: 'city-service',
  },
  'outdoor-kitchens-boise': {
    hero: '/images/blog/outdoor-kitchens-boise.webp',
    alt: "Built-in outdoor kitchen with a grill, stone counters, and seating on a covered patio in a Boise backyard",
    topicTags: ["outdoor","kitchen","boise"],
    source: 'blog',
  },
  'covered-patios-boise': {
    hero: '/images/blog/covered-patios-boise.webp',
    alt: "Covered patio with a solid roof, outdoor furniture, and lighting extending outdoor living at a Boise home",
    topicTags: ["outdoor","patio","boise"],
    source: 'blog',
  },
  'decks-vs-patios-boise': {
    hero: '/images/gallery/gallery-outdoor-before.webp',
    alt: 'Backyard deck and patio options for Boise outdoor living',
    topicTags: ["outdoor","deck","patio"],
    source: 'gallery',
  },
  'outdoor-fireplaces-boise': {
    hero: '/images/blog/outdoor-fireplaces-boise.webp',
    alt: 'Outdoor fireplace on a covered patio for year-round Treasure Valley entertaining',
    topicTags: ["outdoor","fireplace","boise"],
    source: 'blog',
  },
  'outdoor-entertaining-spaces': {
    hero: '/images/city-service/adu__eagle.webp',
    alt: 'Outdoor entertaining area adjacent to an Eagle home with seating and shade',
    topicTags: ["outdoor","entertaining","eagle"],
    source: 'city-service',
  },
  'luxury-outdoor-living': {
    hero: '/images/city-service/adu__nampa.webp',
    alt: 'Luxury outdoor living space with premium finishes in the Treasure Valley',
    topicTags: ["outdoor","luxury","nampa"],
    source: 'city-service',
  },
  'backyard-transformations-boise': {
    hero: '/images/city-service/adu__kuna.webp',
    alt: 'Transformed backyard with hardscape and plantings in Kuna',
    topicTags: ["outdoor","backyard","kuna"],
    source: 'city-service',
  },
  'boise-remodeling-cost-guide': {
    hero: '/images/gallery/gallery-whole-home-after.webp',
    alt: 'Treasure Valley remodel cost planning guide featuring whole-home renovation context',
    topicTags: ["cost","guide","pillar"],
    source: 'gallery',
  },
  'treasure-valley-remodeling-guide': {
    hero: '/images/areas/boise.webp',
    alt: 'Treasure Valley neighborhoods and homes served by Boise Remodeling Co',
    topicTags: ["location","treasure-valley","guide"],
    source: 'areas',
  },
  'boise-remodeling-guide': {
    hero: '/images/blog/boise-remodeling-guide.webp',
    alt: 'Boise homes and neighborhoods for remodeling projects across the North End and Bench',
    topicTags: ["location","boise","guide"],
    source: 'blog',
  },
  'boise-kitchen-remodeling-guide': {
    hero: '/images/services/kitchen-remodel.webp',
    alt: 'Complete Boise kitchen remodeling guide with layouts, materials, and timelines',
    topicTags: ["kitchen","guide","pillar"],
    source: 'services',
  },
  'boise-bathroom-remodeling-guide': {
    hero: '/images/services/bathroom-remodel.webp',
    alt: 'Boise bathroom remodeling guide covering showers, layouts, and aging-in-place',
    topicTags: ["bathroom","guide","pillar"],
    source: 'services',
  },
  'boise-home-addition-guide': {
    hero: '/images/services/room-addition.webp',
    alt: 'Boise home addition guide for second stories, suites, and ADUs',
    topicTags: ["addition","guide","pillar"],
    source: 'services',
  },
  'boise-adu-guide': {
    hero: '/images/services/adu.webp',
    alt: 'Boise ADU guide covering zoning rules, costs, and detached guest house construction',
    topicTags: ["adu","guide","pillar"],
    source: 'services',
  },
  'whole-home-remodeling-guide': {
    hero: '/images/services/whole-home-remodel.webp',
    alt: 'Whole home remodeling guide for Treasure Valley homeowners',
    topicTags: ["whole-home","guide","pillar"],
    source: 'services',
  },
  'choose-remodeling-contractor-boise': {
    hero: '/images/blog/choose-remodeling-contractor-boise.webp',
    alt: 'Choosing a trusted remodeling contractor in Boise and the Treasure Valley',
    topicTags: ["contractor","guide","pillar"],
    source: 'blog',
  },
  'boise-remodeling-process-guide': {
    hero: '/images/blog/boise-remodeling-process-guide.webp',
    alt: 'Boise remodeling process from consultation through warranty walkthrough',
    topicTags: ["process","guide","pillar"],
    source: 'blog',
  },
  'best-remodeling-roi-boise': {
    hero: '/images/blog/best-remodeling-roi-boise.webp',
    alt: 'Best remodeling projects for ROI in Boise homes',
    topicTags: ["roi","guide","pillar"],
    source: 'blog',
  },
  'outdoor-living-remodeling-guide': {
    hero: '/images/gallery/gallery-outdoor-after.webp',
    alt: 'Outdoor living remodeling guide for patios, kitchens, and backyards in Boise',
    topicTags: ["outdoor","guide","pillar"],
    source: 'gallery',
  },
  'meridian-remodeling-guide': {
    hero: '/images/areas/meridian.webp',
    alt: 'Meridian subdivision homes and remodeling context in Ada County',
    topicTags: ["location","meridian","guide"],
    source: 'areas',
  },
  'eagle-remodeling-guide': {
    hero: '/images/areas/eagle.webp',
    alt: 'Eagle executive homes and remodeling opportunities in the Foothills',
    topicTags: ["location","eagle","guide"],
    source: 'areas',
  },
  'kuna-remodeling-guide': {
    hero: '/images/areas/kuna.webp',
    alt: 'Kuna family homes and newer construction suited for remodeling',
    topicTags: ["location","kuna","guide"],
    source: 'areas',
  },
  'star-remodeling-guide': {
    hero: '/images/areas/star.webp',
    alt: 'Star-area homes and rural-suburban remodeling in Ada County',
    topicTags: ["location","star","guide"],
    source: 'areas',
  },
  'middleton-remodeling-guide': {
    hero: '/images/areas/middleton.webp',
    alt: 'Middleton homes in Canyon County with remodeling and permit context',
    topicTags: ["location","middleton","guide"],
    source: 'areas',
  },
  'nampa-remodeling-guide': {
    hero: '/images/areas/nampa.webp',
    alt: 'Nampa homes and Canyon County remodeling considerations',
    topicTags: ["location","nampa","guide"],
    source: 'areas',
  },
  'caldwell-remodeling-guide': {
    hero: '/images/areas/caldwell.webp',
    alt: 'Caldwell homes and Canyon County remodeling context near downtown and the College of Idaho',
    topicTags: ["location","caldwell","guide"],
    source: 'areas',
  },
  'north-end-remodeling-guide': {
    hero: '/images/blog/north-end-remodeling-guide.webp',
    alt: 'Historic North End craftsman bungalows and period-appropriate remodels in Boise',
    topicTags: ["location","north-end","neighborhood","guide"],
    source: 'blog',
  },
  'boise-bench-remodeling-guide': {
    hero: '/images/blog/boise-bench-remodeling-guide.webp',
    alt: 'Mid-century ranch homes on the Boise Bench suited for kitchen and bath updates',
    topicTags: ["location","bench","neighborhood","guide"],
    source: 'blog',
  },
  'harris-ranch-remodeling-guide': {
    hero: '/images/blog/harris-ranch-remodeling-guide.webp',
    alt: 'Harris Ranch planned community homes in Southeast Boise',
    topicTags: ["location","harris-ranch","neighborhood","guide"],
    source: 'blog',
  },
  'east-boise-remodeling-guide': {
    hero: '/images/blog/east-boise-remodeling-guide.webp',
    alt: 'East Boise neighborhoods with varied housing stock for remodeling',
    topicTags: ["location","east-boise","neighborhood","guide"],
    source: 'blog',
  },
  'hidden-springs-remodeling-guide': {
    hero: '/images/blog/hidden-springs-remodeling-guide.webp',
    alt: 'Hidden Springs community homes in the Boise foothills',
    topicTags: ["location","hidden-springs","neighborhood","guide"],
    source: 'blog',
  },
  'eagle-foothills-remodeling-guide': {
    hero: '/images/blog/eagle-foothills-remodeling-guide.webp',
    alt: 'Eagle Foothills custom homes with mountain views and premium remodel potential',
    topicTags: ["location","eagle-foothills","neighborhood","guide"],
    source: 'blog',
  },
};

export const HUB_HERO_IMAGES: Record<string, string> = {
  'remodeling-costs': '/images/gallery/gallery-whole-home-after.webp',
  'kitchen-remodeling': '/images/services/kitchen-remodel.webp',
  'bathroom-remodeling': '/images/services/bathroom-remodel.webp',
  'home-additions': '/images/services/room-addition.webp',
  'whole-home-remodeling': '/images/services/whole-home-remodel.webp',
  'contractor-selection': '/images/blog/choose-remodeling-contractor-boise.webp',
  'remodeling-process': '/images/blog/boise-remodeling-process-guide.webp',
  'remodeling-roi': '/images/blog/best-remodeling-roi-boise.webp',
  'outdoor-living': '/images/gallery/gallery-outdoor-before.webp',
  'treasure-valley-locations': '/images/areas/boise.webp',
};

/** Slugs that need files copied to public/images/blog/ (see scripts/setup-blog-images.mjs) */
export const BLOG_ASSET_COPY_MAP: Record<string, string> = {
  'boise-remodeling-guide': '/images/areas/boise.webp',
  'choose-remodeling-contractor-boise': '/images/process-design-review.webp',
  'boise-remodeling-process-guide': '/images/gallery/gallery-whole-home-before.webp',
  'best-remodeling-roi-boise': '/images/gallery/gallery-kitchen-after.webp',
  // Neighborhood guides now ship bespoke, neighborhood-appropriate hero photos
  // (each reflects that area's housing stock) instead of reusing a shared area
  // or city-service photo, so they are intentionally not derived copies here.
  'eagle-foothills-remodeling-guide': '/images/areas/eagle.webp',
};
